-- qconcursos.questaoresidencia definition

CREATE TABLE `questaoresidencia` (
  `questao_id` int NOT NULL AUTO_INCREMENT,
  `gabarito` varchar(10) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `codigo` int NOT NULL,
  `enunciado` text,
  `alternativaA` varchar(1000) DEFAULT NULL,
  `alternativaB` varchar(1000) DEFAULT NULL,
  `alternativaC` varchar(1000) DEFAULT NULL,
  `alternativaD` varchar(1000) DEFAULT NULL,
  `alternativaE` varchar(1000) DEFAULT NULL,
  `gabarito_texto` varchar(1000) DEFAULT NULL,
  `gabaritoIA` varchar(10) DEFAULT NULL,
  `comentario` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `comentarioIA` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `comentario_autor` varchar(255) DEFAULT NULL,
  `comentario_data` date DEFAULT NULL,
  `ano` int DEFAULT NULL,
  `hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `instituicao` varchar(255) DEFAULT NULL,
  `nivel` varchar(255) DEFAULT NULL,
  `numero` int DEFAULT NULL,
  `prova` varchar(255) DEFAULT NULL,
  `uf` varchar(255) DEFAULT NULL,
  `duplicata` bit(1) DEFAULT NULL,
  `tem_imagem` bit(1) DEFAULT b'0',
  `qtde_imagens` int DEFAULT NULL,
  `dificuldade` int DEFAULT '0',
  `taxaAcerto` int DEFAULT '0',
  `classificacoes` varchar(1000) DEFAULT NULL,
  `area` varchar(255) DEFAULT NULL,
  `comentario_tem_imagem` bit(1) DEFAULT b'0',
  PRIMARY KEY (`questao_id`),
  UNIQUE KEY `codigo_UNIQUE` (`codigo`) /*!80000 INVISIBLE */,
  KEY `questaoresidencia_hash_IDX` (`hash`) USING BTREE,
  FULLTEXT KEY `searchIndex` (`enunciado`,`gabarito_texto`),
  FULLTEXT KEY `gabaritoTextoIndex` (`gabarito_texto`),
  FULLTEXT KEY `enunciadoIndex` (`enunciado`),
  FULLTEXT KEY `classificacoesIndex` (`classificacoes`),
  FULLTEXT KEY `questaoresidencia_comentario_IDX` (`comentario`)
) ENGINE=InnoDB AUTO_INCREMENT=444476 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;