-- qconcursos.questaomedicina definition

CREATE TABLE `questaomedicina` (
  `questao_id` int NOT NULL DEFAULT '0',
  `codigo` int NOT NULL,
  `alternativaA` varchar(1000) DEFAULT NULL,
  `alternativaB` varchar(1000) DEFAULT NULL,
  `alternativaC` varchar(1000) DEFAULT NULL,
  `alternativaD` varchar(1000) DEFAULT NULL,
  `alternativaE` varchar(1000) DEFAULT NULL,
  `ano` int DEFAULT NULL,
  `instituicao` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `dificuldade` int DEFAULT '0',
  `enunciado` text NOT NULL,
  `gabarito` varchar(6) DEFAULT NULL,
  `classificacoes` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `duplicata` bit(1) DEFAULT b'0',
  `hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `comentarioHTML` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `nivel` int DEFAULT '0',
  `comentario_autor` varchar(255) DEFAULT NULL,
  `acertosAltA` int DEFAULT '0',
  `acertosAltB` int DEFAULT '0',
  `acertosAltC` int DEFAULT '0',
  `acertosAltD` int DEFAULT '0',
  `acertosAltE` int DEFAULT '0',
  `taxaAcerto` double DEFAULT '0',
  `categoria_categoria_id` int DEFAULT NULL,
  `gabarito_texto` varchar(10000) DEFAULT NULL,
  `gabaritoIA` varchar(10) DEFAULT NULL,
  `area` varchar(45) DEFAULT NULL,
  `tem_imagem` bit(1) DEFAULT b'0',
  `comentario` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `comentario_tem_imagem` bit(1) DEFAULT b'0',
  PRIMARY KEY (`questao_id`),
  UNIQUE KEY `codigo` (`codigo`),
  FULLTEXT KEY `searchIndex` (`enunciado`,`gabarito_texto`),
  FULLTEXT KEY `gabaritoTextoIndex` (`gabarito_texto`),
  FULLTEXT KEY `enunciadoIndex` (`enunciado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;